
spring:
  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  thymeleaf:
    cache: false
    mode: HTML
server:
  port: 9090